function [methodinfo,structs,enuminfo,ThunkLibName]=libOptimize
%LIBOPTIMIZE Create structures to define interfaces found in 'BlasHeader'.

%This function was generated by loadlibrary.m parser version 1.1.6.38 on Mon Sep 23 15:39:32 2013
%perl options:'BlasHeader.i -outfile=libOptimize.m -thunkfile=libOptimize_thunk_maci64.c -header=BlasHeader.h'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival,'thunkname', ival);
MfilePath=fileparts(mfilename('fullpath'));
ThunkLibName=fullfile(MfilePath,'libOptimize_thunk_maci64');
% int matlabEntry ( double * , double * , int ); 
fcns.thunkname{fcnNum}='int32voidPtrvoidPtrint32Thunk';fcns.name{fcnNum}='matlabEntry'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'doublePtr', 'doublePtr', 'int32'};fcnNum=fcnNum+1;
methodinfo=fcns;